// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

/*
Package proto_csmsg is a generated protocol buffer package.

It is generated from these files:
	demo.proto

It has these top-level messages:
	CS_Login
	SCLogin
*/
package proto_csmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MSG_ID int32

const (
	MSG_ID_MSG_ID_CS_None  MSG_ID = 0
	MSG_ID_MSG_ID_CS_Login MSG_ID = 10001
	MSG_ID_MSG_ID_SC_LogIn MSG_ID = 10002
)

var MSG_ID_name = map[int32]string{
	0:     "MSG_ID_CS_None",
	10001: "MSG_ID_CS_Login",
	10002: "MSG_ID_SC_LogIn",
}
var MSG_ID_value = map[string]int32{
	"MSG_ID_CS_None":  0,
	"MSG_ID_CS_Login": 10001,
	"MSG_ID_SC_LogIn": 10002,
}

func (x MSG_ID) String() string {
	return proto.EnumName(MSG_ID_name, int32(x))
}
func (MSG_ID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// MSG_ID_CS_Login = 10001;
type CS_Login struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *CS_Login) Reset()                    { *m = CS_Login{} }
func (m *CS_Login) String() string            { return proto.CompactTextString(m) }
func (*CS_Login) ProtoMessage()               {}
func (*CS_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CS_Login) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// MSG_ID_SC_LogIn = 10002;
type SCLogin struct {
}

func (m *SCLogin) Reset()                    { *m = SCLogin{} }
func (m *SCLogin) String() string            { return proto.CompactTextString(m) }
func (*SCLogin) ProtoMessage()               {}
func (*SCLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*CS_Login)(nil), "proto_csmsg.CS_Login")
	proto.RegisterType((*SCLogin)(nil), "proto_csmsg.SC_login")
	proto.RegisterEnum("proto_csmsg.MSG_ID", MSG_ID_name, MSG_ID_value)
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x06, 0x53, 0xf1, 0xc9, 0xc5, 0xb9, 0xc5, 0xe9,
	0x4a, 0x2a, 0x5c, 0x1c, 0xce, 0xc1, 0xf1, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0x42, 0x12, 0x5c, 0xec,
	0x89, 0xc9, 0xc9, 0xf9, 0xa5, 0x79, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae,
	0x12, 0x17, 0x17, 0x47, 0xb0, 0x73, 0x7c, 0x0e, 0x48, 0x95, 0x96, 0x07, 0x17, 0x9b, 0x6f, 0xb0,
	0x7b, 0xbc, 0xa7, 0x8b, 0x90, 0x10, 0x17, 0x1f, 0x84, 0x15, 0xef, 0x1c, 0x1c, 0xef, 0x97, 0x9f,
	0x97, 0x2a, 0xc0, 0x20, 0x24, 0xc2, 0xc5, 0x8f, 0x10, 0x03, 0x1b, 0x2b, 0x30, 0xd1, 0x0f, 0x49,
	0x34, 0xd8, 0x19, 0x24, 0xea, 0x99, 0x27, 0x30, 0xc9, 0xcf, 0x49, 0x38, 0x4a, 0x10, 0xec, 0x14,
	0x7d, 0x24, 0x07, 0x25, 0xb1, 0x81, 0x39, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x87, 0xbd,
	0x77, 0x4a, 0xb2, 0x00, 0x00, 0x00,
}
