// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

/*
Package proto_csmsg is a generated protocol buffer package.

It is generated from these files:
	demo.proto

It has these top-level messages:
	CS_Login
	SCLogin
	CS_MoveInfo
	InputState
	MoveInfo
*/
package proto_csmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MSG_ID int32

const (
	MSG_ID_MSG_ID_CS_None     MSG_ID = 0
	MSG_ID_MSG_ID_CS_Login    MSG_ID = 10001
	MSG_ID_MSG_ID_SC_LogIn    MSG_ID = 10002
	MSG_ID_MSG_ID_CS_MoveInfo MSG_ID = 20001
)

var MSG_ID_name = map[int32]string{
	0:     "MSG_ID_CS_None",
	10001: "MSG_ID_CS_Login",
	10002: "MSG_ID_SC_LogIn",
	20001: "MSG_ID_CS_MoveInfo",
}
var MSG_ID_value = map[string]int32{
	"MSG_ID_CS_None":     0,
	"MSG_ID_CS_Login":    10001,
	"MSG_ID_SC_LogIn":    10002,
	"MSG_ID_CS_MoveInfo": 20001,
}

func (x MSG_ID) String() string {
	return proto.EnumName(MSG_ID_name, int32(x))
}
func (MSG_ID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// MSG_ID_CS_Login = 10001;
type CS_Login struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *CS_Login) Reset()                    { *m = CS_Login{} }
func (m *CS_Login) String() string            { return proto.CompactTextString(m) }
func (*CS_Login) ProtoMessage()               {}
func (*CS_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CS_Login) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// MSG_ID_SC_LogIn = 10002;
type SCLogin struct {
}

func (m *SCLogin) Reset()                    { *m = SCLogin{} }
func (m *SCLogin) String() string            { return proto.CompactTextString(m) }
func (*SCLogin) ProtoMessage()               {}
func (*SCLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// MSG_ID_CS_MoveIfo = 20001;
type CS_MoveInfo struct {
	MoveInfo []*MoveInfo `protobuf:"bytes,1,rep,name=moveInfo" json:"moveInfo,omitempty"`
}

func (m *CS_MoveInfo) Reset()                    { *m = CS_MoveInfo{} }
func (m *CS_MoveInfo) String() string            { return proto.CompactTextString(m) }
func (*CS_MoveInfo) ProtoMessage()               {}
func (*CS_MoveInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CS_MoveInfo) GetMoveInfo() []*MoveInfo {
	if m != nil {
		return m.MoveInfo
	}
	return nil
}

type InputState struct {
	Up    bool `protobuf:"varint,1,opt,name=up" json:"up,omitempty"`
	Down  bool `protobuf:"varint,2,opt,name=down" json:"down,omitempty"`
	Left  bool `protobuf:"varint,3,opt,name=left" json:"left,omitempty"`
	Right bool `protobuf:"varint,4,opt,name=right" json:"right,omitempty"`
}

func (m *InputState) Reset()                    { *m = InputState{} }
func (m *InputState) String() string            { return proto.CompactTextString(m) }
func (*InputState) ProtoMessage()               {}
func (*InputState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InputState) GetUp() bool {
	if m != nil {
		return m.Up
	}
	return false
}

func (m *InputState) GetDown() bool {
	if m != nil {
		return m.Down
	}
	return false
}

func (m *InputState) GetLeft() bool {
	if m != nil {
		return m.Left
	}
	return false
}

func (m *InputState) GetRight() bool {
	if m != nil {
		return m.Right
	}
	return false
}

type MoveInfo struct {
	InputState *InputState `protobuf:"bytes,1,opt,name=inputState" json:"inputState,omitempty"`
	// s
	Tm int64 `protobuf:"varint,2,opt,name=tm" json:"tm,omitempty"`
	// ms
	Delta int64 `protobuf:"varint,3,opt,name=delta" json:"delta,omitempty"`
}

func (m *MoveInfo) Reset()                    { *m = MoveInfo{} }
func (m *MoveInfo) String() string            { return proto.CompactTextString(m) }
func (*MoveInfo) ProtoMessage()               {}
func (*MoveInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MoveInfo) GetInputState() *InputState {
	if m != nil {
		return m.InputState
	}
	return nil
}

func (m *MoveInfo) GetTm() int64 {
	if m != nil {
		return m.Tm
	}
	return 0
}

func (m *MoveInfo) GetDelta() int64 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func init() {
	proto.RegisterType((*CS_Login)(nil), "proto_csmsg.CS_Login")
	proto.RegisterType((*SCLogin)(nil), "proto_csmsg.SC_login")
	proto.RegisterType((*CS_MoveInfo)(nil), "proto_csmsg.CS_MoveInfo")
	proto.RegisterType((*InputState)(nil), "proto_csmsg.InputState")
	proto.RegisterType((*MoveInfo)(nil), "proto_csmsg.MoveInfo")
	proto.RegisterEnum("proto_csmsg.MSG_ID", MSG_ID_name, MSG_ID_value)
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x49, 0x52, 0x4a, 0xb8, 0x91, 0x4a, 0xb8, 0x14, 0xe1, 0xb1, 0x8a, 0x18, 0x2a, 0x86,
	0x22, 0xca, 0xc0, 0x8a, 0x08, 0x12, 0x8a, 0x44, 0x3b, 0xd8, 0x5b, 0x17, 0xab, 0x3f, 0x6e, 0x89,
	0x94, 0xd8, 0x51, 0xeb, 0xc0, 0x73, 0xc0, 0xcc, 0xc2, 0x9b, 0x22, 0x3b, 0xe4, 0x87, 0xc9, 0xf7,
	0x7c, 0x3a, 0xd2, 0xf9, 0x64, 0x80, 0x8d, 0xc8, 0xd5, 0xa4, 0xd8, 0x2b, 0xad, 0x30, 0xb0, 0x0f,
	0x5f, 0x1f, 0xf2, 0xc3, 0x2e, 0xba, 0x06, 0x3f, 0x66, 0xfc, 0x55, 0xed, 0x52, 0x89, 0x04, 0x4e,
	0x96, 0xeb, 0xb5, 0x2a, 0xa5, 0x26, 0xce, 0xc8, 0x19, 0x9f, 0xd2, 0x3a, 0x46, 0x00, 0x3e, 0x8b,
	0x79, 0x66, 0x5a, 0xd1, 0x23, 0x04, 0x31, 0xe3, 0x33, 0xf5, 0x2e, 0x12, 0xb9, 0x55, 0x78, 0x07,
	0x7e, 0xfe, 0x77, 0x13, 0x67, 0xe4, 0x8d, 0x83, 0xe9, 0xe5, 0xa4, 0x33, 0x30, 0xa9, 0x8b, 0xb4,
	0xa9, 0x45, 0x0b, 0x80, 0x44, 0x16, 0xa5, 0x66, 0x7a, 0xa9, 0x05, 0x0e, 0xc0, 0x2d, 0x0b, 0x3b,
	0xe8, 0x53, 0xb7, 0x2c, 0x10, 0xa1, 0xb7, 0x51, 0x1f, 0x92, 0xb8, 0x96, 0xd8, 0xdb, 0xb0, 0x4c,
	0x6c, 0x35, 0xf1, 0x2a, 0x66, 0x6e, 0x1c, 0xc2, 0xf1, 0x3e, 0xdd, 0xbd, 0x69, 0xd2, 0xb3, 0xb0,
	0x0a, 0x51, 0x0a, 0x7e, 0xa3, 0xf6, 0x00, 0x90, 0x36, 0x3b, 0x76, 0x21, 0x98, 0x5e, 0xfd, 0x93,
	0x6b, 0x35, 0x68, 0xa7, 0x6a, 0x94, 0x74, 0x6e, 0x05, 0x3c, 0xea, 0xea, 0xdc, 0x4c, 0x6d, 0x44,
	0xa6, 0x97, 0x76, 0xdf, 0xa3, 0x55, 0xb8, 0x59, 0x41, 0x7f, 0xc6, 0x5e, 0x78, 0xf2, 0x8c, 0x08,
	0x83, 0xea, 0xe2, 0x31, 0xe3, 0x73, 0x25, 0x45, 0x78, 0x84, 0x43, 0x38, 0x6b, 0x99, 0xfd, 0xdf,
	0xf0, 0x73, 0xde, 0xa1, 0x2c, 0x36, 0x34, 0x91, 0xe1, 0xd7, 0x1c, 0x09, 0x60, 0xdb, 0xad, 0xf5,
	0xc3, 0x9f, 0x6f, 0xe7, 0xe9, 0x62, 0x71, 0x6e, 0x7d, 0x6f, 0x3b, 0xd6, 0xab, 0xbe, 0x0d, 0xf7,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0x5b, 0xee, 0xbd, 0xd5, 0x01, 0x00, 0x00,
}
